-- Spec §13: the detailed engine's factors were hard-coded in pricing.js. They are now
-- admin-editable settings, seeded here with the values the engine previously used.
insert into pricing_settings (key, value, description, category) values
  ('component_min_walls', '42000', 'Minimum charge in cents for walls', 'component_minimum'),
  ('component_min_ceilings', '26000', 'Minimum charge in cents for ceilings', 'component_minimum'),
  ('component_min_doors', '18000', 'Minimum charge in cents for doors', 'component_minimum'),
  ('component_min_windows', '16000', 'Minimum charge in cents for windows', 'component_minimum'),
  ('component_min_radiators', '14000', 'Minimum charge in cents for radiators', 'component_minimum'),
  ('component_min_baseboards', '12000', 'Minimum charge in cents for baseboards', 'component_minimum'),
  ('component_min_facade', '90000', 'Minimum charge in cents for facade', 'component_minimum'),
  ('component_min_railings', '18000', 'Minimum charge in cents for railings', 'component_minimum'),
  ('component_min_stairs', '22000', 'Minimum charge in cents for stairs', 'component_minimum'),
  ('component_min_other', '18000', 'Minimum charge in cents for other', 'component_minimum'),
  ('property_multiplier_apartment', '1', 'Price multiplier for property type: apartment', 'property_multiplier'),
  ('property_multiplier_house', '1.08', 'Price multiplier for property type: house', 'property_multiplier'),
  ('property_multiplier_commercial', '1.16', 'Price multiplier for property type: commercial', 'property_multiplier'),
  ('property_multiplier_facade', '1.2', 'Price multiplier for property type: facade', 'property_multiplier'),
  ('property_multiplier_room', '0.92', 'Price multiplier for property type: room', 'property_multiplier'),
  ('property_multiplier_other', '1.05', 'Price multiplier for property type: other', 'property_multiplier'),
  ('service_factor_ceiling_paint_2_coats', '1', 'Service weighting factor: ceiling paint 2 coats', 'service_factor'),
  ('service_factor_wall_paint_2_coats', '1', 'Service weighting factor: wall paint 2 coats', 'service_factor'),
  ('service_factor_remove_wallpaper', '0.46', 'Service weighting factor: remove wallpaper', 'service_factor'),
  ('service_factor_apply_wallpaper', '1.18', 'Service weighting factor: apply wallpaper', 'service_factor'),
  ('service_factor_filling_spackling', '0.52', 'Service weighting factor: filling spackling', 'service_factor'),
  ('service_factor_mold_treatment', '0.7', 'Service weighting factor: mold treatment', 'service_factor'),
  ('service_factor_nicotine_treatment', '0.62', 'Service weighting factor: nicotine treatment', 'service_factor'),
  ('service_factor_water_damage_repair', '0.86', 'Service weighting factor: water damage repair', 'service_factor'),
  ('service_factor_priming_sealing', '0.38', 'Service weighting factor: priming sealing', 'service_factor'),
  ('service_factor_covering_protection', '0.22', 'Service weighting factor: covering protection', 'service_factor'),
  ('service_factor_paint_railings', '0.85', 'Service weighting factor: paint railings', 'service_factor'),
  ('service_factor_paint_stairs', '0.95', 'Service weighting factor: paint stairs', 'service_factor'),
  ('service_factor_paint_doors', '0.9', 'Service weighting factor: paint doors', 'service_factor'),
  ('service_factor_paint_windows', '0.85', 'Service weighting factor: paint windows', 'service_factor'),
  ('service_factor_paint_radiators', '0.8', 'Service weighting factor: paint radiators', 'service_factor'),
  ('service_factor_paint_baseboards', '0.6', 'Service weighting factor: paint baseboards', 'service_factor'),
  ('service_factor_paint_other', '0.8', 'Service weighting factor: paint other', 'service_factor'),
  ('quantity_weight_walls', '1850', 'Price per unit in cents for walls', 'quantity_rule'),
  ('quantity_min_walls', '12', 'Minimum billable quantity for walls', 'quantity_rule'),
  ('quantity_weight_ceilings', '1600', 'Price per unit in cents for ceilings', 'quantity_rule'),
  ('quantity_min_ceilings', '8', 'Minimum billable quantity for ceilings', 'quantity_rule'),
  ('quantity_weight_doors', '14500', 'Price per unit in cents for doors', 'quantity_rule'),
  ('quantity_min_doors', '1', 'Minimum billable quantity for doors', 'quantity_rule'),
  ('quantity_weight_windows', '11000', 'Price per unit in cents for windows', 'quantity_rule'),
  ('quantity_min_windows', '1', 'Minimum billable quantity for windows', 'quantity_rule'),
  ('quantity_weight_radiators', '12500', 'Price per unit in cents for radiators', 'quantity_rule'),
  ('quantity_min_radiators', '1', 'Minimum billable quantity for radiators', 'quantity_rule'),
  ('quantity_weight_baseboards', '1650', 'Price per unit in cents for baseboards', 'quantity_rule'),
  ('quantity_min_baseboards', '8', 'Minimum billable quantity for baseboards', 'quantity_rule'),
  ('quantity_weight_facade', '2850', 'Price per unit in cents for facade', 'quantity_rule'),
  ('quantity_min_facade', '25', 'Minimum billable quantity for facade', 'quantity_rule'),
  ('quantity_weight_railings', '6500', 'Price per unit in cents for railings', 'quantity_rule'),
  ('quantity_min_railings', '2', 'Minimum billable quantity for railings', 'quantity_rule'),
  ('quantity_weight_stairs', '4500', 'Price per unit in cents for stairs', 'quantity_rule'),
  ('quantity_min_stairs', '5', 'Minimum billable quantity for stairs', 'quantity_rule'),
  ('quantity_weight_other', '18000', 'Price per unit in cents for other', 'quantity_rule'),
  ('quantity_min_other', '1', 'Minimum billable quantity for other', 'quantity_rule'),
  ('service_factor_default', '0.35', 'Fallback weighting for services with no explicit factor', 'service_factor'),
  ('preparation_surcharge', '1.18', 'Surcharge when preparation services are selected', 'detailed_engine'),
  ('large_project_discount', '0.94', 'Multiplier for large projects', 'detailed_engine'),
  ('small_project_surcharge', '1.12', 'Multiplier for small projects', 'detailed_engine'),
  ('detailed_minimum_cents', '65000', 'Absolute minimum for a detailed quote, in cents', 'detailed_engine')
on conflict (key) do nothing;
